title: "Prywes Lab"
description: "Synthetic biology and enzymology"
url: "https://pryweslab.org"
baseurl: ""
footer: ""
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
header_pages:
  - index.md
  - about.md
  - people.md
  - publications.md
  - join-us.md